package com.npick.common.error;

public enum ErrorType {
    BAD_REQUEST,
    LENGTH_REQUIRED,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    RANGE_NOT_SATISFIABLE,
    SERVICE_UNAVAILABLE,
    INTERNAL_SERVER_ERROR
}
